r = 0.05;          % discounting
sigma = 0.25;     % volatility
mu_G = 0.15;         % productivity of green capital
mu_B = 0.25;          % productivity of brown capital
gamma = 5;          % risk aversion coefficient
theta = 0.5;          % g(z,a) sensitivity to state z
a_bar = 0.3;         % maximum value of effort to change z
lambda = 0.02;      % Poisson intensity parameter
omega = 0.05;           % green preference parameter
tau = 0.25;          % tax on brown/ subsidy on green